import Image from "next/image";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ini Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h1>Hello Word</h1>
    </div>
  );
}
