import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ini Profile",
  description: "Generated by create next app",
};

export default function Profile() {
  return (
    <div>
      <h1>Profile</h1>
    </div>
  );
}
